services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Crooks@2025"
    platform: "linux/amd64"
    ports:
      - "1433:1433"


